### ISSUE TITLE
Cov 

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#356] opened 2016-08-11 07:04 UTC
I realise Change regional boundaries #228 covers this but this was something we agreed with the planners in Cov. I realise a Metro region is planned but it won't involve much cycling between Cov & Birmingham area as there is a green belt. However, there is cycling between Cov and Warwickshire. The current bondaries do look wrong.

**Comment by Robinlovelace** [comment] 2016-08-11 10:00
Closing as it's a duplicate of https://github.com/npct/pct-shiny/issues/228

**Closed by Robinlovelace** 2016-08-11 10:00 UTC
