### ISSUE TITLE
automated checking procedure to see if tool crashes for any region and scenario

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#188] opened 2016-04-11 17:39 UTC
would be nice. We can't manually check every region & every combination of display and scenarios

**Comment by Robinlovelace** [comment] 2016-04-12 08:13
Agreed - will save us loads of time. Seems someone's made a package to make that easy: http://stackoverflow.com/questions/36338779/unit-testing-shiny-apps @nikolai-b you up for taking a look?

**Comment by Robinlovelace** [comment] 2016-04-28 21:19
This is a duplicate of https://github.com/npct/pct-load/issues/27

**Closed by Robinlovelace** 2016-04-28 21:19 UTC
