### ISSUE TITLE
route network has some segments with zero cyclists

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#331] opened 2016-08-08 07:13 UTC
see the attached example – some segments that have cyclists in the previous regional build now have zero cyclists.

Otherwise the route network numbers look good
[Pct.docx](https://github.com/npct/pct-shiny/files/406248/Pct.docx)

**Comment by RachelAldred** [comment] 2016-08-08 08:06
Also I noticed on zooming in that the 'zero cyclists' and some other lines are displayed twice (as if we were showing both directions, but some have different numbers). Have attached screenshot showing one example where one of these 'doubled' lines is zero and one (with the popup) has a positive number.
[RN_pic.docx](https://github.com/npct/pct-shiny/files/406322/RN_pic.docx)

Anna if you want to send me the correct area and lines file for Cambridgeshire, I am happy to test the numbers too if needed.
(The route network looks a little gappy, we'll need to ensure people don't interpret it as 'oh we can build along that A road leaving a gap in the middle'!)

**Comment by Robinlovelace** [comment] 2016-08-08 18:27
Fixed here: https://github.com/npct/pct-load/commit/dc05991093fc49097dd2ed5b8a46a48699020e2a 

@RachelAldred I think your comment is a duplicate of this: https://github.com/npct/pct-shiny/issues/333

**Closed by Robinlovelace** 2016-08-08 18:27 UTC
