### ISSUE TITLE
warwickshire: coventry missing

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#459] opened 2016-11-24 15:56 UTC
test server has a reversion relative to pct.bike, coventry is missing from warwickshire which is not correct

**Comment by JDWoodcock** [comment] 2016-11-24 15:59
oh no

**Comment by AnnaGoodman1** [comment] 2016-11-24 16:01
ha, yes I know this one is close to your heart James! but should be easy to fix, I hope... (most of nat build looking good)

**Comment by Robinlovelace** [comment] 2016-11-25 13:37
Heads up @JDWoodcock, this reversion seems to have been introduced accidentally by @usr110 here: https://github.com/npct/pct-shiny/commit/c71ecb853b32c01ab926f0d446ab4551d98c800b Ali please check your work before pushing - this seems to have changed the regional boundaries I fixed in the national build and will require some time to fix :(

**Closed** 2016-11-29 19:11 UTC

**Comment by usr110** [comment] 2016-11-30 13:14
@Robinlovelace I don't think my changes have anything to do with it; I've just modified the `url` property of each region (which was `wiltshire` in all cases). Please make sure that you identify the problem first.

**Comment by Robinlovelace** [comment] 2016-11-30 13:41
I'm sure the boundaries changed, but I incorrectly stated it was due to your commit, apologies @usr110.

In fact it seems that it was @nikolai-b that introduced this bug, as illustrated below:

![screenshot from 2016-11-30 13-35-11](https://cloud.githubusercontent.com/assets/1825120/20754234/e954da46-b701-11e6-9e8c-51f95b92c14a.png)

 Reproducible example below (please try to reproduce Ali and Nikolai and let me know - great to have this ability to go back to the commit history, a great advantage of using version control):

```r
u1 = "https://github.com/npct/pct-shiny/raw/960e30f73eef898843c2283e86e2f506fccb1d05/regions_www/regions.geojson"
regions_nikolai = geojsonio::geojson_read(u1, "web", what = "sp")
sp::plot(regions_nikolai[regions_nikolai$Region == "west-midlands",])

u2 = "https://github.com/npct/pct-shiny/raw/b3c85b798ad4269f4fa5092a2e3badb24457f66c/regions_www/regions.geojson"
regions_nikolai2 = geojsonio::geojson_read(u2, "web", what = "sp")
sp::plot(regions_nikolai2[regions_nikolai2$Region == "west-midlands",])
```

Nikolai's original commit was right, his later one was wrong: https://github.com/npct/pct-shiny/blob/960e30f73eef898843c2283e86e2f506fccb1d05/regions_www/regions.geojson


![screenshot from 2016-11-30 13-40-30](https://cloud.githubusercontent.com/assets/1825120/20754388/96175a60-b702-11e6-9603-6ce4ae871f23.png)

![screenshot from 2016-11-30 13-38-07](https://cloud.githubusercontent.com/assets/1825120/20754327/5bda1fea-b702-11e6-83c0-8ef9069eb67f.png)

**Comment by usr110** [comment] 2016-11-30 16:15
Thanks Robin for the clarification and the investigation.
