### ISSUE TITLE
Subset lines to only include those with dist_fast < 30km

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#314] opened 2016-07-19 11:49 UTC
This should be done when we generate the new national lines dataset.

**Comment by AnnaGoodman1** [comment] 2016-07-19 13:15
Yes - and check that the resulting lines after this filtering all find a match when merging with the dataset I provided. This could just possibly not happen if CycleStreets gave slightly different distance estimates at different times which pushed it across the 30km threshold, e.g. giving an estimate of 30.01 km back in January and 29.9 km now - such a line would not be present in the lines that I have provided.  If this happened it would be very easy to fix – I would just change the line in question to having a distance of 29.9 km in my dataset and then recalculate the lines.   This could either be checked at the point of merging, or could be checked after the region had been built by making sure that scenario data was present for all lines in the CSV download file

**Comment by AnnaGoodman1** [comment] 2016-08-08 06:59
duplicate of#330

**Closed by AnnaGoodman1** 2016-08-08 06:59 UTC
