### ISSUE TITLE
IMD map not working

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#663] opened 2018-10-30 17:51 UTC
colours no longer showing, maybe an issue with the tiles? (spotted it, but not spent any time trying to fix)

![untitled](https://user-images.githubusercontent.com/11818225/47739057-70180080-dc6c-11e8-8335-8243e9d282eb.png)

**Comment by Robinlovelace** [comment] 2018-10-31 06:16
Closing as duplicate of #661 - fix is straightforward. I wanted to check that the new address supplied by Oliver was stable. I checked via email and the answer was yes so the plan (discussed with @nikolai-b) is to switch to this new tileset to fix the issue. Good nudge - don't see any reason not to fix now.

**Closed by Robinlovelace** 2018-10-31 06:16 UTC
