### ISSUE TITLE
"your connection is not secure" pct message (?), if accessed from LA map

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#587] opened 2017-04-11 12:59 UTC
@usr110 (cc @Robinlovelace , @nikolai-b ): When I go to the local authority map  https://pct.bike/la-map.html and then click on the icon in the bottom right-hand corner, to take me to the PCT, I get this security alert message saying 'the website is not configured properly' (see below).  I think it is possibly to do with the fact that I let the LA map access my location details, to use the 'zoom in on where I am' function on the local authority map. Is there some way to fix this ? If not (or until it is fixed) I suggest the bottom in the right-hand corner of the LA map could be disabled so that people don't get this nasty security alert message!

![image](https://cloud.githubusercontent.com/assets/11818225/24910116/974afb0c-1ebe-11e7-8cb9-ef48c0365319.png)

Thanks!

**Comment by Robinlovelace** [comment] 2017-04-11 13:06
Assigning to @usr110 as it's related to the LA map - not worked on this but it's looking great overall aside from this issue and the search bar - many thanks for flagging.

**Comment by usr110** [comment] 2017-04-11 13:07
This was 'caused, I believe, in this commit by @nikolai-b 
https://github.com/npct/pct-shiny/commit/659090708e159c8aff5caa61a907a67c7a91f9ac#diff-ab6b6cde9215e78913a29781184526ffL592

It's caused by insecure elements in the landing page. Now that we are moving towards `https` for the entire application, until that's done,, I would suggest to resuse `http` there. What do you think @nikolai-b ?

**Comment by Robinlovelace** [comment] 2017-04-11 13:12
Ah yes - https'ing everything seems to have some unintended consequences - yes please switch the culprits (if you can identify them) back to http. Great to be testing well in advance of this going live and perhaps we should rethink whether *everything* needs to be https as Ali says.

**Comment by Robinlovelace** [comment] 2017-04-11 13:31
Working on it - cc @usr110

**Comment by usr110** [comment] 2017-04-11 13:38
Robin, thanks but it's a certificate issue. Best Nikolai deals with it (he's already on it).

**Comment by Robinlovelace** [comment] 2017-04-11 13:39
Ah OK - will re-assign to him then - cheers.

**Comment by usr110** [comment] 2017-04-11 13:42
@nikolai-b has fixed the issue. Please give it a try. Thanks Nikolai

**Closed by usr110** 2017-04-11 13:42 UTC

**Comment by Robinlovelace** [comment] 2017-04-11 13:49
Checked: fixed.
