### ISSUE TITLE
distances not right on GM layer or lines showing in wrong places

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#438] opened 2016-11-13 10:41 UTC
well the lines now show but the lines highlighted are all over the place and the distances for each line are not right (some very long lines with short distances and vice versa) or the lines are not showing in the right places e.g the names of msoas are right but the wrong msoas are shown as connected.

looking more closely it is the latter- the lines are in the wrong place
[tests.docx](https://github.com/npct/pct-shiny/files/587701/tests.docx)
prob relates to problem we had before of areas moving around!
see attached.
@audev  and in case your fix affected this @nikolai-b

**Comment by audev** [comment] 2016-11-13 11:10
@JDWoodcock  I noticed. Seems the problem is in the distances link to the lines so the wrong distances are showing.
I'm regenerating distances so probably today this will be fixed. I'll let you but it'll be later on.

**Comment by nikolai-b** [comment] 2016-11-13 18:40
I guessed the co-ordinate reference system (CRS) for the Manchester all-lines data and it might not be right so the incorrect plotting of the lines is possibly due to that.  Spatial data needs to have a CRS, how was the lines file generated? If it created with a CRS again it will fail again.

**Comment by audev** [comment] 2016-11-13 21:47
Thanks for clarifying, yes, I guessed it after seeing your commit ( rf/rq needed to be regenerated for a different reason). I get l.rds needs CRS system, which now I'm adding in my builds. 
One thing though that needs to be clear is *when* adding CRS: it seems you just run proj4string(l) and that fixes <l> (i.e. you could also run it upstream, before running buildregion.R).
I'm asking because I committed CRS data and still got issues so not sure if it takes time to propagate to server or sth is wrong. 
I'll test it tomorrow to see how it goes.

**Comment by AnnaGoodman1** [comment] 2016-11-23 07:39
I think now fixed

**Closed by AnnaGoodman1** 2016-11-23 07:39 UTC
