### ISSUE TITLE
National build issues - isle of wight/general

### ISSUE THREAD

**Issue by AnnaGoodman1** [npct/pct-shiny#439] opened 2016-11-13 11:37 UTC
Malcolm emailed me to say that a new version of Isle of Wight was ready for testing, but unfortunately there seem to be a large number of problems with the version currently on the test server – see attached word doc.  These include the fact that I don’t think the fast and quiet routes have been correctly merged based on their ID - so possibly we will still need to consider the backup plan of rerunning the 226,103 lines that should get displayed on the screens.  

If we do simply rerun the sub-set of lines that might get displayed on the interface, then the attached file 161111_NatLinesSet (in the zip file) shows the 226,103 lines that I think ought to be re-run (I also sent his round on Friday). If we do we run these then I will need to regenerate the scenario numbers (but won’t need to update the appendices in the paper), and provide a new version of pct_area/pct_lines - this would probably only take me a day or so, so would not need to slow us down much.  

If we manage to fix the merging issue and use the current set of lines, then we need to
a)	Rerun as quiet routes the 2584 lines in the attached file ’ 161113_MissingQuietLines’; these fail to route in Malcolm’s first attempt, almost all of them relate to just a few MSOAs in West London so probably the program just had a bit of a glitch at that point. We would need to be run down as presumably at the moment they would come up as straight lines on the interface for anyone looking at West London.
b)	merge in the corrected hilliness data, which I’ve put in the attached data file ‘161113_CorrectHilliness_rf_rq’. At the moment the correct hilliness data is not present in the interface.

I’m happy to do more testing whenever new versions are available, and to help in any other way I can.
[161112_PCTisleofWight.docx](https://github.com/npct/pct-shiny/files/587719/161112_PCTisleofWight.docx)
[csv_files_zip.zip](https://github.com/npct/pct-shiny/files/587720/csv_files_zip.zip)

**Comment by nikolai-b** [comment] 2016-11-13 18:53
@mem48 I believe what you have done is run
https://github.com/npct/pct-load/blob/master/R/generate_lines_iterate.R
then run
https://github.com/npct/pct-load/blob/master/R/merge_annas_into_lines.R
Is that correct?  I don't really follow the build process but I think it needs to be:

- Get all the MSOA - MSOA pairs and run `od2line` on them and save this as `l_nat.Rds`
- Get the fast and slow routes from cyclesscape using `line2route` and from the order of `l_nat.Rds` and the routes we can give each route the MOSA - MSOA id (i.e. nothing can happen to lines that doesn't happen to routes or they won't match and I'm worried about https://github.com/npct/pct-load/blob/master/R/generate_lines_iterate.R#L86 )
- Merge Anna's data into `l_nat`, any lines not in Anna's can be dropped from the lines and from the corresponding routes.

Maybe this has been done but I thought it would be good to lay it out clearly even for my sake only. I can't find the updated `l_nat.Rds` that generated the routes, has this been put online somewhere?

**Comment by Robinlovelace** [comment] 2016-11-14 10:40
The new lines data are here: https://github.com/npct/pct-bigdata/blob/master/lines_oneway_shapes_updated.Rds

The challenge is to get the equivalent lines - I thought that had been completed.

Any updates on this @mem48? Will take a look if not but will be useful to get a quick summary of where we're at before Wednesday.

**Comment by mem48** [comment] 2016-11-14 12:03
@nikolai-b The build Process is:

**Input Data:**
../pct-bigdata/cents-scenarios.geojson
../pct-bigdata/wu03ew_msoa.zip/wu03ew_msoa.csv
**Run** 
https://github.com/npct/pct-load/blob/master/R/generate_lines.R 
This was done several times for subsets based on distance (0-5,5-10,10-20,20-30) and again for lines anna siad was missing
**Output:**
../msoa_rerun/oldway/rq_EW_XXX.Rds 
../msoa_rerun/oldway/rf_EW_XXX.Rds
../msoa_rerun/oldway/lines_EW_XXX.Rds
**Run** 
https://github.com/npct/pct-load/blob/master/R/merge_routes_to_single_file.R once for rf / rq / lines
**Output:**
rf_nat_all
rq_nat_all
l_nat_noScens
**Run**
https://github.com/npct/pct-load/blob/master/R/merge_lines_routes.R
For 
**Output:**
rf_nat_id
rq_nat_id
**Run**
https://github.com/npct/pct-load/blob/master/R/Compare_old_to_new.R
For each of rf and rq
**Output:**
rf_nat
rq_nat

**Comment by mem48** [comment] 2016-11-14 12:04
We could avoid a lot of this mess in the future if line2route returned the MSOA-MSOA id field with the result

**Comment by Robinlovelace** [comment] 2016-11-14 12:12
The solution:

```r
rf = line2route(l)
rf$id = l$id
```

`line2route` is designed to output only data received from the route planning APIs - happy for someone to add an argement `id` which could return the 1st column of the l if it's `TRUE` or the corresponding variable if it was a character string. Then it would be:

```r
rf = line2route(l, id = "id")
```

which is fine but it's not clear to me whether the minor additional cost of complexity in the function outweighs the minor additional cost of having to add an extra line to explicitly copy across the id.

**Comment by nikolai-b** [comment] 2016-11-14 23:22
Thanks, that makes sense but there have been lots of changes and code additions that I haven't understood.

If you used https://github.com/npct/pct-load/blob/master/R/generate_lines.R then why did you create https://github.com/npct/pct-load/blob/master/R/generate_lines_iterate.R as I am worried about https://github.com/npct/pct-load/blob/master/R/generate_lines_iterate.R#L86.

Also it seems like @Robinlovelace is saying https://github.com/npct/pct-load/blob/master/R/merge_lines_routes.R should just be:

```R
rf$id = l$id
```

Also @Robinlovelace you are saying that https://github.com/npct/pct-bigdata/commit/923c8e5 added the lines that @mem48 generated when he was getting the routes from Cyclestreets?  Are you sure that is the lines from Malcom and not the One way lines with Anna's new data?

Sorry for all the questions but I'm struggling to follow

**Comment by Robinlovelace** [comment] 2016-11-15 06:16
In answer to the questions directed at me, yes I'm saying that there should never be any 'merging code'. That [script](https://github.com/npct/pct-load/blob/master/R/merge_lines_routes.R) can be replaced by `rf$id = l$id`. 

Regarding the new `lines_oneway_shapes_updated.Rds` file, yes that's the existing geographic lines with the new data.

**Comment by nikolai-b** [comment] 2016-11-15 08:29
Thanks Robin, that clears up a few things!  I've been asking for the `l_nat_noScens` or ideally the `lines_EW_XXX` as these are the lines generated that will match the new `rf_nat` and `rq_nat`, we should then merge Anna's into `l_nat_noScens` and replace `lines_oneway_shapes_updated` entirely.  Also with then it would be easy to check that the rf and rq ids are right.

We assume that lines and the routes match (i.e. are in the same order) but the new routes won't match the old lines.  I'm not sure that assumption is used later on in the code but I would be worried about using a set of old lines and a set of new routes.

Sorry if I'm missing something obvious / repeating myself, I just want to get the big national data sorted before we do a build.

**Comment by audev** [comment] 2016-11-15 17:20
@Robinlovelace  You mention using `rf$id = l$id` to match the routes rf/rq with the lines, this has also caused some confusion in the GM layer. This is OK if you have generated rf/rq with stplanr::line2route on -the-fly.

What if you load the predefined rf, rq?

E.g. say you have the lines 'l' [e.g. 1,000 x 90], and rf, rq built previously, and with an 'id' column in them (which are larger than l, [50,000 x 20], or whatever). Let's assume all the lines in l do exist in rf/rq (l$id %in% rf$id  TRUE for all lines). But could rf/rq have been generated in a different order, does this matter at all?

So when you subset rf,rq here:
[https://github.com/npct/pct-load/blob/master/build_region.R#L83] (url)

does this sort automatically rf-rq, so that the 3 files=l-rf-rq are perfectly aligned?  Does this not depend on the order the file 'l' used to generate the predefined rf/rq ?

My understanding would be that to be able to use the lines below [https://github.com/npct/pct-load/blob/master/build_region.R#L100](url)  you need to reorder first rf/rq ?

Thanks,

**Comment by Robinlovelace** [comment] 2016-11-16 08:46
Hi @audev, this issue is separate from this national build issue.

Whenever you save routed data, it makes sense to save the id as you say.

That way, when linking pre-generated routes with lines, you can use something like:

```r
sel_rf = rf_nat$id %in% l$id
rf = rf_nat[sel_rf,]
```
It makes sense to check the order and total number of lines also but that's a good start. If you have generated `rf`/`rq` files that lack ids, as Malcolm did, I suggest you re-add the ids or regenerate the routes.

**Comment by mem48** [comment] 2016-11-16 10:40
It seems that something has gone wrong in my workflow of binding the IDs to the routes, my plan for today is to redo the binding from scratch and try to create a single nice script that does this for the future.

Then if there is time modify stplanr to return IDs and then this will not happen again with the LSOAs

**Comment by audev** [comment] 2016-11-16 11:40
Hi @Robinlovelace       I think both issues are linked. 
Anyway, my question is not about the id (I explicitly said I built rf,rq with id), it's about merging.

- You have l : 9760 flows
- rf, rq (built previously, with id) : 20,000 rows/routes
- You subset as you describe:    rf= rf[ rf$id %in% l$id,    ]

Will rf have the id's in the same order as <l>? If NOT, you will get errors in distances. This should be clarified in buildregion.R

So, do you need to reorder rf before adding all the parameters produced by Cyclestreets to <l> ? Does that reordering of rf@data _extend_ to the Spatial bit as well?

All this comes because, as @mem48 , I just rerun buildregionGM.r (with on the fly line2route), got l-rf-rq, but again _the distances come wrong_.  

So, apart from the merging issues, possibly Cyclestreet is now outputting wrong values too.

**Comment by Robinlovelace** [comment] 2016-11-16 11:51
@mem48 this is now fixed - please try to reproduce (as documented in `?line2route()`):

```r
## Not run: 
data(flowlines)
l = flowlines[2:5,]
rf <- line2route(l = l, "route_cyclestreet", plan = "fastest")
rq <- line2route(l = l, plan = "quietest", silent = TRUE)
plot(rf, col = "red")
plot(rq, col = "green", add = TRUE)
plot(l, add = T)
# Plot for a single line to compare 'fastest' and 'quietest' route
n = 2
plot(l[n,])
lines(rf[n,], col = "red")
lines(rq[n,], col = "green")
# Example with list output
l <- l[1:3,]
rf_list <- line2route(l = l, list_output = TRUE)
class(rf_list)       # list output
class(rf_list[[2]])  # but individual elements are spatial
rf_list_of_lists <- line2route(l = l, list_output = TRUE, save_raw = TRUE)
class(rf_list_of_lists)       # list output
class(rf_list_of_lists[[2]])  # but individual elements are spatial
# illustration of how the l_id argument works:
rf$id # has id as l has "id" field
l$id <- NULL # remove id field for testing
rf_no_id <- line2route(l)
rf_no_id$id # [1] "1" "2" "3" "4"
rf_with_id = line2route(l, l_id = "All")
rf_with_id$id # [1] 38 10 44
```
Hope this helps - slightly more complex but should ensure we copy the ids!

Robin

**Comment by Robinlovelace** [comment] 2016-11-16 11:52
P.s. you'll need to 

```r
devtools::install_github("robinlovelace/stplanr")
```

For this to work...

**Comment by audev** [comment] 2016-11-16 12:35
@Robinlovelace  Hi robin, is 
devtools::install_github("robinlovelace/stplanr")   

different in any way from:

devtools::install_github("ropensci/stplanr")    ?

**Comment by Robinlovelace** [comment] 2016-11-16 12:44
Yes. 

At present, the top of this page tells me my branch is a few commits ahead of the ROpenSci version: https://github.com/ropensci/stplanr

Please see here for a complete diff between the two branches: https://github.com/ropensci/stplanr/pulls

Note also that my PR is failing the automated build process. Any ideas why?

PRs on that to fix things upstream appreciated.

Robin

**Comment by nikolai-b** [comment] 2016-11-21 18:49
Splitting into separate issues.

**Closed by nikolai-b** 2016-11-21 18:49 UTC

**Comment by Robinlovelace** [comment] 2016-11-21 20:55
Good shout to close it - was getting a little rambling this issue.
