### ISSUE TITLE
Explore alternative color schemes for the maps

### ISSUE THREAD

**Issue by Robinlovelace** [npct/pct-shiny#374] opened 2016-08-16 13:19 UTC
This is what we have currently: 
![screenshot from 2016-08-16 14-18-22](https://cloud.githubusercontent.com/assets/1825120/17700112/5337061c-63bc-11e6-99bb-71240d1b3854.png)

This seems intuitive and popular, and is based on this code: 
https://github.com/npct/pct-shiny/blob/master/scripts/mapgen.R#L60

However, it may be worth exploring alternatives, e.g. using the **viridis** package described here: 
https://www.r-bloggers.com/using-the-new-viridis-colormap-in-r-thanks-to-simon-garnier/

I recommend trying out the bottom right of the 6 sub-plots under the "Normal" Vision heading.

**Comment by usr110** [comment] 2016-08-18 14:32
I have created a new similar to the one being used in the application. Once the test server is up again, you will be able to see it here: http://npct0.vs.mythic-beasts.com/new_map.html
It is going to be embedded in the landing page (which will be updated soon)

I am displaying two screenshots with the extreme cases (Census 2011 and Ebikes) as examples below.

**Census 2011**
![front-map-lowest-scenario](https://cloud.githubusercontent.com/assets/10958628/17777176/686363e0-6557-11e6-89fb-c96f426400fd.png)

**Ebikes**
![front-map-highest-scenario](https://cloud.githubusercontent.com/assets/10958628/17777197/7ef5d5e8-6557-11e6-82d1-54b153e06ffd.png)

Re our current colour scheme, I believe it passes all three types of colour blindness: protanopia, deuteranopia, and tritanopia. I've used the guide presented here: http://bconnelly.net/2013/10/creating-colorblind-friendly-figures/

Specifically this figure ![figure](http://bconnelly.net/assets/img/cbfriendly/cb-palette.png)

shows that yellow and green are uniquely identified in all three cases. What do you guys think?

**Comment by Robinlovelace** [comment] 2016-08-18 15:05
I think this is great work and I like the subtlety of it compared with the bold red-green option. However I suspect that, for most people, that will send a clearer and more intuitive message so there are pros and cons for both options. Is there anyway to tweak this colourscheme so that the differences are more pronounced. I definitely think the 'Ebikes' scenario looks better with the current front page map scheme. Would you be up for testing (e.g. on a branch or just a commit that can be reverted) to test out how the red-green scheme looks in the app?

Here's the current (and more attractive IMO) front page with Ebikes - the graduations (which could be made continuous or increased beyond 5) between different %s are much clearer in this case, a major advantage of this kind of scheme:

![frontpage](https://cloud.githubusercontent.com/assets/1825120/17778871/811666ca-655d-11e6-96c0-ca70f14d4625.PNG)

**Comment by usr110** [comment] 2016-08-18 16:23
Robin, thanks for your reply. In the Ebike case, your screenshot does make a more pronounced difference, but the main issue, in my view, is with the colour-scale that it is confusing (going from red to green with light yellow in between). Most of the scales I've seen go from light to dark colour, which isn't the case here.

Solution: instead of trying new different combinations one by one I'd recommend everyone use this amazing website http://colorbrewer2.org/ and then agree on one colour schemes which is used throughout.
This allows us to select not only single and multiple hues, but more importantly, it allows to restrict selection which is colour blind friendly which serves our purpose. 
I am still happy with the application's colour scheme. If others don't like, we can switch to another scheme. 
After trying out multiple combinations, I personally like this one:

http://colorbrewer2.org/#type=sequential&scheme=OrRd&n=5

Which is, more or less, used in this case: http://jackdougherty.github.io/leaflet-map-polygon-hover/index.html

**Comment by AnnaGoodman1** [comment] 2016-08-19 11:18
I like this one, which is similar to Robin's front page.... though not colour blind friendly...
http://colorbrewer2.org/#type=diverging&scheme=RdYlGn&n=11

My main concern is that 'low cycling' looks the same colour as our 'straight lines' is at present, so might need to tweak that to a different shade.

As an alternative, I also like Ali's new front page that is consistent with the current region.

**Comment by mem48** [comment] 2016-08-22 10:35
How about http://colorbrewer2.org/#type=diverging&scheme=RdBu&n=9 it is colour blind safe and with 9 distinct colours could cover both high-cycle and low-cycle areas.

**Comment by Robinlovelace** [comment] 2016-08-22 10:39
I like the look of that one - a strong contender IMO. Will be good to see a quick prototype of what the app would look like if that were implemented - I'm sure the front page map would be the same as it's essentially the same as the one that is already in use, http://colorbrewer2.org/#type=diverging&scheme=RdYlGn&n=11

**Comment by AnnaGoodman1** [comment] 2016-08-22 11:44
or http://colorbrewer2.org/#type=diverging&scheme=RdYlBu&n=11

**Comment by Robinlovelace** [comment] 2016-08-22 14:40
Just pushed a test branch to test this - will send screenshots from train soon: https://github.com/npct/pct-shiny/tree/test-new-colours

**Comment by Robinlovelace** [comment] 2016-08-22 16:53
Heads up @npct/admin I've managed to create an integrated scale for the front map and regional app:

Building on Anna's suggestion but with n = 9: http://colorbrewer2.org/#type=diverging&scheme=RdYlBu&n=9

In the app: 

![screenshot from 2016-08-22 17-48-11](https://cloud.githubusercontent.com/assets/1825120/17863331/2579b84e-6891-11e6-8f1c-4d6f9b9b7000.png)


On the front page map:

![Uploading Screenshot from 2016-08-22 17-40-58.png…]()

**Comment by Robinlovelace** [comment] 2016-08-22 17:02
To test drive the new front page map, see here: http://rpubs.com/RobinLovelace/203560

Just pushed the code for this: https://github.com/npct/pct-shiny/tree/test-new-colours

**Comment by AnnaGoodman1** [comment] 2016-08-23 05:18
i like how this looks a lot - amazing, and great, that it does not interfere with our existing lines.

I am broadly happy with the bins on the key but not so keen on having numbers repeated, e.g. '6-8', '8-10'.  I think people will find that confusing.  Also there is a mismatch witht he way we present % on screen in the popups - in the popups we have % as 'nearest whole number' whereas the key has essentially 'rounded down' (I think, am assuming 6-8% means 6-7.99999%).  So this means sometimes an area with 6% written in the pop-up comes into the 4-6 band and sometimes the 6-8% band.  Again, not as user-friendly

To make things easier for people I suggest we use the following nearest whole number bins, with the following labels
<0.5% 
1% 
2-3%
4-5%
6-7%
8-9%
10-13%
14-19%
20%+

these would all be calculated using rounding to nearest number, i.e. 4-5% is 3.5 to 5.4999, and so the numbers in the key match those that people see on the popup - i.e. 6% on the popup is always in the 6-7% band. 

Note that the '<0.5%' category is not so common for commuter cycling but good to have as will be much more common for 'all trips' cycling (for which commuting is a smaller % trips)

**Comment by Robinlovelace** [comment] 2016-08-23 08:00
Hi Anna, I agree we should think about modifying the bins but not the labelling system. This has been discussed before and I think it's the clearest way of representing the data. We could simply say "(whole numbers numbers are rounded up)" or "(the upper bound means up to but not including)" but there are virtually no whole numbers so I think that additional text would not be worth it. I'd rather be precise and deal with people who as, "but what about cases where it's exactly 10?" than providing incorrect information in the bins. Note the strategy proposed by Anna also requires long-winded description (e.g. "(rounded down to the nearest whole number)" and is not intuitive I don't think.

Anna, could you provide an example from the map where the bins are ambigous? Note that we're using the same (1dp) rounding for the display as for the allocation to bins - I suggest setting that to 2 d.p. - that way there are no marginal cases that I can see.

In terms of the bins, I would suggest setting them as:

```r
zone_fill_breaks = c(0, 1, 2, 4, 6, 10, 15, 20, 30, 60) / 100 # The bins used for the scale
```
I think that's better than what we have currently:

```
zone_fill_breaks = c(0, 1, 2, 4, 6, 8, 10, 14, 20, 60) / 100 # The bins used for the scale
```

https://github.com/npct/pct-shiny/blob/master/pct-shiny-funs.R#L16

**Comment by AnnaGoodman1** [comment] 2016-08-23 13:03
I can't see that  "rounded to the nearest whole number" is more long-winded than "the upper bound means up to but not including" - it is both shorter and in my opinion more intuitive.  ("Whole numbers are rounded up" would not be understandable by me).  And what I'm suggesting is no less precisely defined than what you currently have.  But the main point about what I'm proposing is that it makes the labelling system and the bins comparable to what we do in the pop-ups.  If "6%" in the pop-up means "5.5% to 6.499%", Ie rounding to the nearest whole number, then we should use the same system in defining the bins.  It seems silly to me to use "rounding to the nearest whole number" as the rounding method for the pop-ups and "rounding down" in the bins.   Among other things, it means that a zone labelled in the pop-ups as having "6%" cycling will be two different colours depending on whether it is just above or just below 6.0, which is currently the case. I think this is needlessly confusing, as more generally is switching between different rounding systems in different places.  
so  I suggest something like
zone_fill_breaks = c(0, 0.5, 1.5, 3.5, 5.5, 9.5, 14.5, 19.5, 30.5, 60) / 100 

As another point, although I like the scale a lot in general, would it be possible to modify the colour of the lightest blue to make it more distinct from the background grey colour of unselected zones? As in the attached example, the light blue areas initially looked to me as if they were the same colour as the grey zone outside the selected region, and made me think that some regions of the same were missing (to the point where I was genuinely confused, and worried there was a fault with the build).  Having this first blue a bit more blue would hopefully solve this.


Lastly, I also think we should consider switching the scale and having red the meaning high cycling.  I know that red can mean either "high" or "bad" (currently it means the latter), but I think we should consider having it mean "high". This will be useful if in the future we want to extend the map functionality to include other things, e.g. be able to switch to show the level of driving.  But I'm happy to follow the majority opinion on this.

**Comment by Robinlovelace** [comment] 2016-08-23 14:12
Thanks for this - quick replies:

- it's easy to switch the direction so that red is high, if that's something we want to go for (mildly in favour of blue or even green being high but happy either way and one to discuss)
- it's not so easy to make custom versions of the colour schemes but happy for someone else to do the work 
- re. custom bins, it's good to have a diversity of opinions and debate on this, I personally like the whole number ones and think the guys in RStudio/leaflet who designed (some of whom are lecturers in Statistics) thought carefully about the different options before opting for this one. It would be extra work to change them and I'm not currently 100% sure how to create custom bin labels (tried in vein the first time we had this debate) but imagine it could be done. It would be a bit of a fudge but if we can see an example with it working that looks good and everyone agrees is unambiguous I'd be happy to go for it.

Thanks for your response to my suggested tweaks to the bin extents - the reason I suggested the original was to ensure diversity of colours at the top of the range but I subsequently decided that the jump from 6 to 10 was quite large and that's where we want fine detail but fine if you'd like to revert back to my original 'big jump' suggestion.

**Comment by AnnaGoodman1** [comment] 2016-08-23 14:53
Thanks Robin.  So are you saying that the issue is that if one uses eg the breaks "zone_fill_breaks = c(0, 0.5, 1.5, 3.5, 5.5, 9.5, 14.5, 19.5, 30.5, 60) / 100" then those bins can be created without a problem but the labels automatically produced do not look nice, and we don't know how to overwrite the auto-produced labels with text of our own wording?  If so thendoes anyone else know how to customise the text of the labels? @usr110 , could you look at this?

And any volunteers for having a go at tweaking the first blue colour in the spectrum (#e0f3f8) to become slightly more distincitve from the grey background?  I think that #c6dbef might work, but not sure how to put it in to test it

**Comment by Robinlovelace** [comment] 2016-08-23 17:03
Yes those bins can be created without problem and this is how it looks:

![screenshot from 2016-08-23 17-47-40](https://cloud.githubusercontent.com/assets/1825120/17901106/e27b06dc-6959-11e6-81a7-eb55d0f485a3.png)

Regarding the bin *breaks* I think it's useful to know where there's < 0.5% cycling in Bradford but think overall < 1% is a more useful bin meaning 'very low levels of cycling' so prefer the 0 - 1 bin. (Note that in reality this means 0 =< pcycle < 1, which is clunky to write and hard for many people to understand, hence the decision of the designers of leaflet to use 0 - 1.)

Regarding the bin *labels*  I tried to test your suggestion for testing but it simply didn't change the labels compared with the above (any ideas why @usr110 or @nikolai-b?):

```r
      addLegend(pal = colorBin("RdYlBu", regions$pcycle, bins = zone_fill_breaks * 100, pretty = TRUE),
                position = c("topleft"), values = regions$pcycle, title = "% Cycling\nto work", opacity = 0.5,
                labels = c("<0.5%",
                           "1%",
                           "2-3%",
                           "4-5%",
                           "6-7%",
                           "8-9%",
                           "10-13%",
                           "14-19%",
                           "20%+"))
  )
```

As I say I'm against this bin labelling option - can go into all the reasons why but for now it's sufficient to say that they are technical, in terms of code complexity and ease of reproducibility for others using leaflet (the most popular open source mapping library on the internet), aesthetic and pedagogic. 

Regarding the text to clarify it, I've had a think. "(0 - 1 means <= x < 1)" would be a concise and correct hover-over text to show and put in the manual. Even more concise would be "(0 - 1 means 0 - 0.99..)" which I like because it's intuitive. I think that's more concise and intuitive than the alternative that have decimal bin breaks.

**Comment by AnnaGoodman1** [comment] 2016-08-24 05:48
thanks Robin, that is appreciated.  if @usr110 or @nikolai-b can get the labels working but that would still be my preferred option, I appreciate that it makes the code more complex but I think having "rounding to the nearest whole number" as the rounding method throughout it will make the interface more user-friendly, and more internally consistent. indeed, I think I probably also prefer what it currently looks like to the previous bins, even without the new labels.  Perhaps one to discuss atthe next meeting.

in terms of the category <0.5%, this is mostly just to be able to have whole number rounding – I agree that not that many areas have such very low cycling for commuting. However it will become more relevant for other sorts of cycling.

**Comment by JDWoodcock** [comment] 2016-08-24 09:42
hi 
i worry that with the new approach we lose seeing the range for the scenario and area. Can't we use a new clearer colour scheme but keep the old flexible appraoch? The new appraoch gives less information.
I also dont like 0-1 1-2

**Comment by usr110** [comment] 2016-08-24 11:07
Anna, I've introduced a new legend based on your recommendations (it is non-overlapping). Please see it on the test server.
Robin, the commit is here: https://github.com/npct/pct-shiny/commit/3d503843accfb3cab308c199f260e4ee115fc0d3

The problem with legend labels was being caused by `regions$pcycle` variable. Since, for now, we are displaying a static legend, we don't need to use it in the legend. Personally I would prefer a dynamic legend based on the values being shown.

**Comment by Robinlovelace** [comment] 2016-08-24 11:13
Hi Ali, great work updating the legend with the new labels - simpler than I thought and I see now that just creating a fixed legend is the solution. Anna: I must concede, it doesn't look so bad :+1: 

One thing remains though: please can we say "Rounded to the nearest whole number" if you hover over the legend? Would this be easy to implement @usr110? E.g. with **shinyJS**. And we should probably mention it in the manual. Overall it looks like we're moving towards a solution on this.

**Comment by AnnaGoodman1** [comment] 2016-08-24 11:38
That hover option could be good if easy.

In line with James's comment earlier, i agree we should try to collapse some of the bands for low cycling and increase the numbers for high cycling.  Thanks for saying you would look at this Robin – as a starter, it could be something like   "zone_fill_breaks = c(0, 1.5, 3.5, 6.5, 9.5, 14.5, 19.5, 29.5, 39.5, 100) / 100" 

could we also try replacing colour #e0f3f8 with #c6dbef , or is that a lot of work to do?

**Comment by usr110** [comment] 2016-08-24 13:05
@AnnaGoodman1
> could we also try replacing colour #e0f3f8 with #c6dbef , or is that a lot of work to do?

Done in: https://github.com/npct/pct-shiny/commit/66fe529894b5a7c47bf8cfec7b96fafe4b2cd419

The updated legend can already be seen on the test server. I am using these bins:

> zone_fill_breaks = c(0, 0.5, 1.5, 3.5, 5.5, 9.5, 14.5, 19.5, 30.5, 60) / 100 

Do you want them to be replaced with:

> zone_fill_breaks = c(0, 1.5, 3.5, 6.5, 9.5, 14.5, 19.5, 29.5, 39.5, 100) / 100
?

**Comment by Robinlovelace** [comment] 2016-08-24 13:46
I think that would make sense, making the upper bound much higher and making it clear that any level of cycling less than 1.5% is very low - I thought the 0 - 0.5% bin was too small. One option to consider: replace 29.5 with 24.5 to continue the increments of 5 for longer but no strong preference for that, just one to discuss.

**Comment by AnnaGoodman1** [comment] 2016-08-25 14:27
Yes, I agree that replacing the current cut points as per your comment, Ali, would make sense.  I think I prefer 29.5 to 24.5, otherwise the jump from 5% to 15% feels a bit large.  

Good if you can also make the same cut points, and same labels, on your front page map.  Thanks!

**Comment by Robinlovelace** [comment] 2016-08-25 14:32
OK great I think we have clarity. Please set 

```r
zone_fill_breaks = c(0, 1.5, 3.5, 6.5, 9.5, 14.5, 19.5, 29.5, 39.5, 100) / 100
```
As Anna says and update the front page map too if you get a chance Ali.

**Comment by usr110** [comment] 2016-08-25 15:24
On James' suggestion using these bins :

`zone_fill_breaks = c(0, 1.5, 3.5, 6.5, 9.5, 14.5, 19.5, 24.5, 29.5, 100) / 100 `

**Comment by JDWoodcock** [comment] 2016-08-25 15:27
I thought suggested?
zone_fill_breaks = c(0, 1.5, 3.5, 6.5, 9.5, 14.5, 19.5, 24.5, 29.5, 39.5, 100) / 100

**Comment by usr110** [comment] 2016-08-25 15:52
James, the last bin is 40+. Sorry for the confusion. You will shortly see it on the test server.

**Comment by usr110** [comment] 2016-08-25 15:57
@npct/admin The bins and the map are ready (both on the front-page and inside the application). Please test it out. For the curious, fixed the issue in these commits: https://github.com/npct/pct-shiny/commit/2799f93d5eb15988e94169594190b3cb624bc66a https://github.com/npct/pct-shiny/commit/f0adb7f156ee89ae6a76eca41d505987e36e93fd https://github.com/npct/pct-shiny/commit/076c1ae111101bb3241ef69b3d7b3a776a64ff75 https://github.com/npct/pct-shiny/commit/6409a0dabfa25d30d0cc6a2cde3b510457cc66d1 https://github.com/npct/pct-shiny/commit/2cc60eb46a12465c68c2f6474ced065fb162a356 https://github.com/npct/pct-shiny/commit/c1c5443074aa53f52681369ae83f1c0404e7ea6b

Closing this now. If needed, re-open it.

**Closed by usr110** 2016-08-25 15:57 UTC

**Comment by Robinlovelace** [comment] 2016-08-25 22:17
Looks great. And I meant 29.5 in the previous one - all good.
