### ISSUE TITLE
FTP login/being able to install Wordpress plugins

### ISSUE THREAD

**Issue by RachelAldred** [npct/pct-shiny#257] opened 2016-05-23 09:50 UTC
Hi Nikolai, it would be great to have the FTP login or a work-around so I can activate Statcounter and update plugins like spam catching software etc. on the PCT blog :) Thanks.

**Comment by nikolai-b** [comment] 2016-05-24 20:15
@RachelAldred I believe I've done this but let me know if it isn't working.  I've added the details to wordpress internally so it _should_ work automatically.

**Comment by RachelAldred** [comment] 2016-05-29 10:30
Thanks - Statcounter still isn't working so I've emailed them for advice. Other updates seem to be happening.

**Comment by Robinlovelace** [comment] 2016-06-03 11:51
Duplicate of this https://github.com/npct/pct-shiny/issues/267

**Closed by Robinlovelace** 2016-06-03 11:51 UTC
